[build]
  # Base directory is the monorepo root
  command = "npm install && npm run build:frontend"
  # Publish directory for the frontend
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"