[build]
    command = "cd backend && npm run build && cd ../frontend && npm run build"
    publish = "frontend/build"
    functions = "backend/.netlify/functions"

  [[plugins]]
    package = "@netlify/plugin-nextjs"