# netlify.toml
[build]
  command = "cd ./backend && npm run build && cd .. && npm run build"
  publish = "./build"
  functions = "./backend/.netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
   [plugins.inputs]
    baseDir = "backend"
